### ISSUE TITLE
Version in Portuguese

### ISSUE THREAD

**Issue by lubianat** [egonw/SARS-CoV-2-Queries#28]
Hello, Egon,

I have translated the book to Portuguese. 

It was not revised by anyone else, so there might be typos and broken links here and there. 

Nevertheless, I will send a pull request, just in case you would like to add it and/or review it somehow. 

Thanks!
Tiago

**Comment by egonw** [comment]
Awesome! Good news and bad news, tho.

The bad news is that you have been translating the wrong files :( :( :( You need to translate the files in the `src/` folder? Those in `docs/` are compiled.

The good news is that the source files are much shorter: all the tables are autogenerated.

**Comment by egonw** [comment]
See also https://github.com/egonw/SARS-CoV-2-Queries/issues/30

**Comment by lubianat** [comment]
Oh, okay! I thought that might happen somehow but was not sure how. 

No problems, it was fun. I did not translate the tables, so good. 

I will translate the right files next weekend. Thanks!

**Comment by lubianat** [comment]
@egonw I've updated the pull request with the files on the src folder. I am not sure how to compile then into the final version that goes into the docs folder. Any ideas?  

(i have fetched the changes in the last 3 weeks before making the changes)

**Comment by egonw** [comment]
I hooked it in. Check the commits to get some idea. Basically, I run these commands:

```shell
cd sparql; make distclean; make
cd ..; make
```
