### ISSUE TITLE
Virus title issue

### ISSUE THREAD

**Issue by nunogit** [egonw/SARS-CoV-2-Queries#37]
SARS-CoV-2-Queries/blob/master/src/viruses.md

It seems like the virus page title has an issue. It's rendering in common text and not as an h1.  Not sure if, for some reason, this is on purpose.

**Comment by egonw** [comment]
It is a source page. For this file, the "viruses" header is wrapped in XML `<section level="#" label="viruses">Viruses</section>` that is processed when the output Markdown is created.
