### ISSUE TITLE
Make API from SPARQL queries

### ISSUE THREAD

**Issue by c-martinez** [egonw/SARS-CoV-2-Queries#40]
[grlc](https://github.com/CLARIAH/grlc) is a tool to automatically builds Web APIs using SPARQL queries stored in git repositories.

One of the advantages of grlc, is that it can turn a query variable into an API parameter. For example, the language parameter in the [allSARSCoVViruses](https://github.com/egonw/SARS-CoV-2-Queries/blob/master/sparql/allSARSCoVViruses.rq), can be provided as a API parameter -- here is an example:

http://dev.grlc.io/api-git/c-martinez/SARS-CoV-2-Queries/subdir/sparql

And the query can be executed via curl like this:

```
curl -X GET "http://dev.grlc.io/api-git/c-martinez/SARS-CoV-2-Queries/subdir/sparql/allSARSCoVViruses?lang=en%2Cen" -H "accept: text/csv"
```

Would it be useful to migrate all queries in this repo to be compatible with grlc?

**Comment by egonw** [comment]
Okay, I need some further guidance. Why is http://dev.grlc.io/api-git/egonw/SARS-CoV-2-Queries/subdir/docs/grlc not working?

**Comment by egonw** [comment]
Or this one? http://dev.grlc.io/api-git/egonw/SARS-CoV-2-Queries/subdir/grlc

**Comment by egonw** [comment]
Oh, the second is working now (after I added the missing prefixes, I think):

![image](https://user-images.githubusercontent.com/26721/93716450-373ee880-fb70-11ea-9afe-cbf26d43dd95.png)

**Comment by c-martinez** [comment]
I think `http://dev.grlc.io/api-git/egonw/SARS-CoV-2-Queries/subdir/docs/grlc` would not work because only one level subdir is currently supported. I will open an issue about that. But glad to see second one is working. Do get in touch if you need any further help.

**Comment by egonw** [comment]
Okay, for now, I move everything to the root `grlc/` folder, but it's not particularly fast in making the UI and may not be working at all (it wasn't when I just tried): http://dev.grlc.io/api-git/egonw/SARS-CoV-2-Queries/subdir/grlc

**Comment by c-martinez** [comment]
Depending on the number of queries, it may take a while to build the API spec. If it takes too long, the server will time out. I just increased the timeout, which should fix the problem.

**Comment by egonw** [comment]
Okay, it's a start: 

![image](https://user-images.githubusercontent.com/26721/93907969-57041700-fcfe-11ea-83b1-75141c294ef6.png)

But I also note a problem (which I know how to fix):

![image](https://user-images.githubusercontent.com/26721/93908670-37212300-fcff-11ea-8a82-5d79de4ce3d1.png)

**Comment by egonw** [comment]
Okay, going to close the issue. If other things come up, please let me know!
