### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by yayamamo** [egonw/SARS-CoV-2-Queries#9]
I'm translating the contents into Japanese using [GitLocalize](https://gitlocalize.com/).
This app supports i18n for various formats such as Markdown, PO, JSON etc. with synchronizing with a GitHub repo.
Anyone can translate into your mother language with this app, and I setup a project [here](https://gitlocalize.com/repo/4301).
More details please refer [FAQ](https://docs.gitlocalize.com).

**Comment by yayamamo** [comment]
After trying GitLocalize, I found the following pros/cons.
 * Pro
    * Sync with GitHub
    * Markdown support
 * Con
    * It sometimes takes time for an operation due to the limit of GitHub API.
    * You cannot commit your translation work before completing it.

**Comment by egonw** [comment]
I have been doing some testing in this GitHub repo: https://github.com/egonw/l10n-test

The repository actually preprocesses `.i.md` files, which it converted to `.md` files in `docs/`. In those, SPARQL input is already injected. So, I want to update the build process to ensure the SPARQL against Wikidata actually uses that language too.

**Comment by yayamamo** [comment]
I've found another TMS.
https://www.transifex.com/dbcls/sars-cov-2-queries/
If the content to be translated is open, it's free of charge.
As they require me to fill in the institution name, under which translation projects are created, SARS-CoV-2-Queries is currently under dbcls.

**Comment by egonw** [comment]
Thanks for accepting my request for the invitation. I have used Transifex in the past for [CKAN](https://ckan.org/). I'll see if I can get the build system updated this weekend! \

One note, we really have to translate the `*.i.md` files and not those in `docs/`. The latter files are autogenerated.

**Comment by yayamamo** [comment]
Thanks! I've changed the config file with the directory and the extension to `/` and `i.md`, respectively, but the system doesn't seem to recognize this extension. We can see all the markdown files at the root directory to be translated.

**Comment by egonw** [comment]
Regarding the problem that is does not recognize `.i.md` files, that I can solve by putting these files in a `src/` subfolder and just naming them `.md`.

**Comment by yayamamo** [comment]
Thanks, and I created a `src/` folder and copy *.i.md files to it with changing file names. Even though I changed the config file to specify the files to be translated are at the `src/` folder only, there are many i.md files at the transifex resource. Maybe I need to learn how to delete them.

**Comment by egonw** [comment]
Okay, I'm making progress :) I think I have the SPARQLs now run for a set of languages :)

**Comment by egonw** [comment]
Okay, first round results: https://egonw.github.io/SARS-CoV-2-Queries/nl/ :)

So, the content to translate is `src/*.md` and the translated files should be in `src/nl/*.md` (with the same file names). Replace `nl` with the two char code of the language. It may work for something like `nl_NL` too, but have not tested that yet.

**Comment by yayamamo** [comment]
Can I delete all the resources at the transifex except for those in the `src` directory?

**Comment by yayamamo** [comment]
When translating, do I need to reserve the text within the tags of `<sparql>` and `<out>`?

**Comment by egonw** [comment]
Yes, keep all XML code in the files. You're fine to move it around. The "builder" uses this annotation to enrich the file:

* `<sparql>` shows the SPARQL query (and makes a link to the dedicated page, "run"/"edit", etc)
* `<out>` and `<iframe>` show the output of that query
* `<topic>` is used to create the Index at the end of the book
* `<section>` is used to add HTML anchors, allowing you to cite a chapter/section
* `<cite>` takes an Wikidata identifier for a publication
* `<references/>` creates the bibliography at the end of a page

**Comment by yayamamo** [comment]
Thanks, and let me confirm.
The text within the `<topic>` and `</topic>` tags appears literally in the production document, and so I assume I can translate it into its corresponding Japanese text (e.g. `<topic>virus</topic>` to `<topic>ウイルス</topic>`).
However, the text within the `<sparql>` and `</sparql>` tags doesn't appear in the production one, and so I guess it is used to feed an actual SPARQL query.
Therefore, I shouldn't translate it into Japanese, should I?
For example, `<sparql>allSARSCoVViruses</sparql>` shouldn't be translated into `<sparql>全SARSコロナウイルス</sparql>`, is this correct?

**Comment by egonw** [comment]
Ah, good point. Should have mentioned that:

**Content should be translated:**

* `<topic>`
* `<section>` (the @label attribute should not be translated)

**Content should be copied literally untranslated:**

* `<sparql>`
* `<out>` and `<iframe>`
* `<cite>`
* `<references/>`

**Comment by egonw** [comment]
One further comment about `<topic>`. Please adapt where needed to the translation. From past translation work, sometimes it makes sense to use the `<topic>` annotation creatively, to fit how the _full_ sentence is translated. This is, for example, the case when the topic is broken up in words in one language, but not the other.

**Comment by egonw** [comment]
@yayamamo, I think we're almost there. There are two further places that need to become Java property files at some point, but quite manageable at this moment. Can you please translate the following strings used in templates into Japanese, plz?

- [ ] https://github.com/egonw/SARS-CoV-2-Queries/blob/master/makeToC.groovy#L16-L20
- [ ] https://github.com/egonw/SARS-CoV-2-Queries/blob/master/sparql/postprocess#L14-L39

There likely will be one or two more later on.

**Comment by egonw** [comment]
Update: the translations are now linked from each other:

![image](https://user-images.githubusercontent.com/26721/80866260-fd874700-8c8d-11ea-9629-0996a444b7c7.png)

**Comment by egonw** [comment]
Okay, it's all up and running. I'm not excited with the long patches being created by the translation tool, but can isolate the new patches without much effort.
